// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.5
// source: organization-microservice/pb/v1/organization.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ParentOrganizationId string                 `protobuf:"bytes,5,opt,name=parent_organization_id,json=parentOrganizationId,proto3" json:"parent_organization_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Organization) GetParentOrganizationId() string {
	if x != nil {
		return x.ParentOrganizationId
	}
	return ""
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WorkUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkUnit) Reset() {
	*x = WorkUnit{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkUnit) ProtoMessage() {}

func (x *WorkUnit) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkUnit.ProtoReflect.Descriptor instead.
func (*WorkUnit) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *WorkUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkUnit) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *WorkUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkUnit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PositionHierarchy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SuperiorPositionId     string                 `protobuf:"bytes,1,opt,name=superior_position_id,json=superiorPositionId,proto3" json:"superior_position_id,omitempty"`
	SubordinatedPositionId string                 `protobuf:"bytes,2,opt,name=subordinated_position_id,json=subordinatedPositionId,proto3" json:"subordinated_position_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PositionHierarchy) Reset() {
	*x = PositionHierarchy{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionHierarchy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionHierarchy) ProtoMessage() {}

func (x *PositionHierarchy) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionHierarchy.ProtoReflect.Descriptor instead.
func (*PositionHierarchy) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *PositionHierarchy) GetSuperiorPositionId() string {
	if x != nil {
		return x.SuperiorPositionId
	}
	return ""
}

func (x *PositionHierarchy) GetSubordinatedPositionId() string {
	if x != nil {
		return x.SubordinatedPositionId
	}
	return ""
}

type CreateOrganizationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ParentOrganizationId string                 `protobuf:"bytes,4,opt,name=parent_organization_id,json=parentOrganizationId,proto3" json:"parent_organization_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrganizationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrganizationRequest) GetParentOrganizationId() string {
	if x != nil {
		return x.ParentOrganizationId
	}
	return ""
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ListOrganizationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ParentOrganizationId string                 `protobuf:"bytes,2,opt,name=parent_organization_id,json=parentOrganizationId,proto3" json:"parent_organization_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListOrganizationRequest) Reset() {
	*x = ListOrganizationRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationRequest) ProtoMessage() {}

func (x *ListOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrganizationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListOrganizationRequest) GetParentOrganizationId() string {
	if x != nil {
		return x.ParentOrganizationId
	}
	return ""
}

type ListOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationResponse) Reset() {
	*x = ListOrganizationResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationResponse) ProtoMessage() {}

func (x *ListOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrganizationResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type UpdateOrganizationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ParentOrganizationId string                 `protobuf:"bytes,5,opt,name=parent_organization_id,json=parentOrganizationId,proto3" json:"parent_organization_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetParentOrganizationId() string {
	if x != nil {
		return x.ParentOrganizationId
	}
	return ""
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{12}
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepartmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{13}
}

func (x *GetDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentResponse) Reset() {
	*x = GetDepartmentResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentResponse) ProtoMessage() {}

func (x *GetDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{14}
}

func (x *GetDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type ListDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentRequest) Reset() {
	*x = ListDepartmentRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentRequest) ProtoMessage() {}

func (x *ListDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{15}
}

type ListDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentResponse) Reset() {
	*x = ListDepartmentResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentResponse) ProtoMessage() {}

func (x *ListDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{16}
}

func (x *ListDepartmentResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkUnitRequest) Reset() {
	*x = CreateWorkUnitRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkUnitRequest) ProtoMessage() {}

func (x *CreateWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{19}
}

func (x *CreateWorkUnitRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *CreateWorkUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkUnitRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkUnitRequest) Reset() {
	*x = GetWorkUnitRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkUnitRequest) ProtoMessage() {}

func (x *GetWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*GetWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnit      *WorkUnit              `protobuf:"bytes,1,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkUnitResponse) Reset() {
	*x = GetWorkUnitResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkUnitResponse) ProtoMessage() {}

func (x *GetWorkUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkUnitResponse.ProtoReflect.Descriptor instead.
func (*GetWorkUnitResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{21}
}

func (x *GetWorkUnitResponse) GetWorkUnit() *WorkUnit {
	if x != nil {
		return x.WorkUnit
	}
	return nil
}

type ListWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkUnitRequest) Reset() {
	*x = ListWorkUnitRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkUnitRequest) ProtoMessage() {}

func (x *ListWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*ListWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{22}
}

func (x *ListWorkUnitRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type ListWorkUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnits     []*WorkUnit            `protobuf:"bytes,1,rep,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkUnitResponse) Reset() {
	*x = ListWorkUnitResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkUnitResponse) ProtoMessage() {}

func (x *ListWorkUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkUnitResponse.ProtoReflect.Descriptor instead.
func (*ListWorkUnitResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{23}
}

func (x *ListWorkUnitResponse) GetWorkUnits() []*WorkUnit {
	if x != nil {
		return x.WorkUnits
	}
	return nil
}

type UpdateWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkUnitRequest) Reset() {
	*x = UpdateWorkUnitRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkUnitRequest) ProtoMessage() {}

func (x *UpdateWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateWorkUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkUnitRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *UpdateWorkUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkUnitRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkUnitRequest) Reset() {
	*x = DeleteWorkUnitRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkUnitRequest) ProtoMessage() {}

func (x *DeleteWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteWorkUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionRequest) Reset() {
	*x = CreatePositionRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionRequest) ProtoMessage() {}

func (x *CreatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionRequest.ProtoReflect.Descriptor instead.
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{26}
}

func (x *CreatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePositionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{27}
}

func (x *GetPositionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{28}
}

func (x *GetPositionResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type ListPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionRequest) Reset() {
	*x = ListPositionRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionRequest) ProtoMessage() {}

func (x *ListPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionRequest.ProtoReflect.Descriptor instead.
func (*ListPositionRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{29}
}

type ListPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionResponse) Reset() {
	*x = ListPositionResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionResponse) ProtoMessage() {}

func (x *ListPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionResponse.ProtoReflect.Descriptor instead.
func (*ListPositionResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{30}
}

func (x *ListPositionResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{31}
}

func (x *UpdatePositionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePositionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeletePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionRequest) Reset() {
	*x = DeletePositionRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionRequest) ProtoMessage() {}

func (x *DeletePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionRequest.ProtoReflect.Descriptor instead.
func (*DeletePositionRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{32}
}

func (x *DeletePositionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePositionHierarchyRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SuperiorPositionId     string                 `protobuf:"bytes,1,opt,name=superior_position_id,json=superiorPositionId,proto3" json:"superior_position_id,omitempty"`
	SubordinatedPositionId string                 `protobuf:"bytes,2,opt,name=subordinated_position_id,json=subordinatedPositionId,proto3" json:"subordinated_position_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreatePositionHierarchyRequest) Reset() {
	*x = CreatePositionHierarchyRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionHierarchyRequest) ProtoMessage() {}

func (x *CreatePositionHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionHierarchyRequest.ProtoReflect.Descriptor instead.
func (*CreatePositionHierarchyRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{33}
}

func (x *CreatePositionHierarchyRequest) GetSuperiorPositionId() string {
	if x != nil {
		return x.SuperiorPositionId
	}
	return ""
}

func (x *CreatePositionHierarchyRequest) GetSubordinatedPositionId() string {
	if x != nil {
		return x.SubordinatedPositionId
	}
	return ""
}

type GetPositionHierarchyBySuperiorRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SuperiorPositionId string                 `protobuf:"bytes,1,opt,name=superior_position_id,json=superiorPositionId,proto3" json:"superior_position_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPositionHierarchyBySuperiorRequest) Reset() {
	*x = GetPositionHierarchyBySuperiorRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionHierarchyBySuperiorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionHierarchyBySuperiorRequest) ProtoMessage() {}

func (x *GetPositionHierarchyBySuperiorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionHierarchyBySuperiorRequest.ProtoReflect.Descriptor instead.
func (*GetPositionHierarchyBySuperiorRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{34}
}

func (x *GetPositionHierarchyBySuperiorRequest) GetSuperiorPositionId() string {
	if x != nil {
		return x.SuperiorPositionId
	}
	return ""
}

type GetPositionHierarchyBySubordinatedRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SubordinatedPositionId string                 `protobuf:"bytes,1,opt,name=subordinated_position_id,json=subordinatedPositionId,proto3" json:"subordinated_position_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPositionHierarchyBySubordinatedRequest) Reset() {
	*x = GetPositionHierarchyBySubordinatedRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionHierarchyBySubordinatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionHierarchyBySubordinatedRequest) ProtoMessage() {}

func (x *GetPositionHierarchyBySubordinatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionHierarchyBySubordinatedRequest.ProtoReflect.Descriptor instead.
func (*GetPositionHierarchyBySubordinatedRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{35}
}

func (x *GetPositionHierarchyBySubordinatedRequest) GetSubordinatedPositionId() string {
	if x != nil {
		return x.SubordinatedPositionId
	}
	return ""
}

type ListPositionHierarchyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PositionHierarchy []*PositionHierarchy   `protobuf:"bytes,1,rep,name=position_hierarchy,json=positionHierarchy,proto3" json:"position_hierarchy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListPositionHierarchyResponse) Reset() {
	*x = ListPositionHierarchyResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionHierarchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionHierarchyResponse) ProtoMessage() {}

func (x *ListPositionHierarchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionHierarchyResponse.ProtoReflect.Descriptor instead.
func (*ListPositionHierarchyResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{36}
}

func (x *ListPositionHierarchyResponse) GetPositionHierarchy() []*PositionHierarchy {
	if x != nil {
		return x.PositionHierarchy
	}
	return nil
}

type DeletePositionHierarchyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionHierarchyRequest) Reset() {
	*x = DeletePositionHierarchyRequest{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionHierarchyRequest) ProtoMessage() {}

func (x *DeletePositionHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionHierarchyRequest.ProtoReflect.Descriptor instead.
func (*DeletePositionHierarchyRequest) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{37}
}

func (x *DeletePositionHierarchyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPositionHierarchyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PositionHierarchy []*PositionHierarchy   `protobuf:"bytes,1,rep,name=position_hierarchy,json=positionHierarchy,proto3" json:"position_hierarchy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPositionHierarchyResponse) Reset() {
	*x = GetPositionHierarchyResponse{}
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionHierarchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionHierarchyResponse) ProtoMessage() {}

func (x *GetPositionHierarchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_microservice_pb_v1_organization_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionHierarchyResponse.ProtoReflect.Descriptor instead.
func (*GetPositionHierarchyResponse) Descriptor() ([]byte, []int) {
	return file_organization_microservice_pb_v1_organization_proto_rawDescGZIP(), []int{38}
}

func (x *GetPositionHierarchyResponse) GetPositionHierarchy() []*PositionHierarchy {
	if x != nil {
		return x.PositionHierarchy
	}
	return nil
}

var File_organization_microservice_pb_v1_organization_proto protoreflect.FileDescriptor

const file_organization_microservice_pb_v1_organization_proto_rawDesc = "" +
	"\n" +
	"2organization-microservice/pb/v1/organization.proto\x12\x0forganization.v1\"\x9e\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x124\n" +
	"\x16parent_organization_id\x18\x05 \x01(\tR\x14parentOrganizationId\"R\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"u\n" +
	"\bWorkUnit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"P\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x7f\n" +
	"\x11PositionHierarchy\x120\n" +
	"\x14superior_position_id\x18\x01 \x01(\tR\x12superiorPositionId\x128\n" +
	"\x18subordinated_position_id\x18\x02 \x01(\tR\x16subordinatedPositionId\"\x9b\x01\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x124\n" +
	"\x16parent_organization_id\x18\x04 \x01(\tR\x14parentOrganizationId\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x17GetOrganizationResponse\x12A\n" +
	"\forganization\x18\x01 \x01(\v2\x1d.organization.v1.OrganizationR\forganization\"c\n" +
	"\x17ListOrganizationRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\x16parent_organization_id\x18\x02 \x01(\tR\x14parentOrganizationId\"_\n" +
	"\x18ListOrganizationResponse\x12C\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1d.organization.v1.OrganizationR\rorganizations\"\xab\x01\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x124\n" +
	"\x16parent_organization_id\x18\x05 \x01(\tR\x14parentOrganizationId\"+\n" +
	"\x19DeleteOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x17CreateDepartmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"&\n" +
	"\x14GetDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x15GetDepartmentResponse\x12;\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x1b.organization.v1.DepartmentR\n" +
	"department\"\x17\n" +
	"\x15ListDepartmentRequest\"W\n" +
	"\x16ListDepartmentResponse\x12=\n" +
	"\vdepartments\x18\x01 \x03(\v2\x1b.organization.v1.DepartmentR\vdepartments\"_\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x15CreateWorkUnitRequest\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"$\n" +
	"\x12GetWorkUnitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x13GetWorkUnitResponse\x126\n" +
	"\twork_unit\x18\x01 \x01(\v2\x19.organization.v1.WorkUnitR\bworkUnit\":\n" +
	"\x13ListWorkUnitRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\"P\n" +
	"\x14ListWorkUnitResponse\x128\n" +
	"\n" +
	"work_units\x18\x01 \x03(\v2\x19.organization.v1.WorkUnitR\tworkUnits\"\x82\x01\n" +
	"\x15UpdateWorkUnitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"'\n" +
	"\x15DeleteWorkUnitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x15CreatePositionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"$\n" +
	"\x12GetPositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x13GetPositionResponse\x125\n" +
	"\bPosition\x18\x01 \x01(\v2\x19.organization.v1.PositionR\bPosition\"\x15\n" +
	"\x13ListPositionRequest\"O\n" +
	"\x14ListPositionResponse\x127\n" +
	"\tpositions\x18\x01 \x03(\v2\x19.organization.v1.PositionR\tpositions\"]\n" +
	"\x15UpdatePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"'\n" +
	"\x15DeletePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x1eCreatePositionHierarchyRequest\x120\n" +
	"\x14superior_position_id\x18\x01 \x01(\tR\x12superiorPositionId\x128\n" +
	"\x18subordinated_position_id\x18\x02 \x01(\tR\x16subordinatedPositionId\"Y\n" +
	"%GetPositionHierarchyBySuperiorRequest\x120\n" +
	"\x14superior_position_id\x18\x01 \x01(\tR\x12superiorPositionId\"e\n" +
	")GetPositionHierarchyBySubordinatedRequest\x128\n" +
	"\x18subordinated_position_id\x18\x01 \x01(\tR\x16subordinatedPositionId\"r\n" +
	"\x1dListPositionHierarchyResponse\x12Q\n" +
	"\x12position_hierarchy\x18\x01 \x03(\v2\".organization.v1.PositionHierarchyR\x11positionHierarchy\"0\n" +
	"\x1eDeletePositionHierarchyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x1cGetPositionHierarchyResponse\x12Q\n" +
	"\x12position_hierarchy\x18\x01 \x03(\v2\".organization.v1.PositionHierarchyR\x11positionHierarchy2\x9e\x12\n" +
	"\x13OrganizationService\x12a\n" +
	"\x12CreateOrganization\x12*.organization.v1.CreateOrganizationRequest\x1a\x1d.organization.v1.Organization\"\x00\x12f\n" +
	"\x0fGetOrganization\x12'.organization.v1.GetOrganizationRequest\x1a(.organization.v1.GetOrganizationResponse\"\x00\x12i\n" +
	"\x10ListOrganization\x12(.organization.v1.ListOrganizationRequest\x1a).organization.v1.ListOrganizationResponse\"\x00\x12a\n" +
	"\x12UpdateOrganization\x12*.organization.v1.UpdateOrganizationRequest\x1a\x1d.organization.v1.Organization\"\x00\x12a\n" +
	"\x12DeleteOrganization\x12*.organization.v1.DeleteOrganizationRequest\x1a\x1d.organization.v1.Organization\"\x00\x12[\n" +
	"\x10CreateDepartment\x12(.organization.v1.CreateDepartmentRequest\x1a\x1b.organization.v1.Department\"\x00\x12`\n" +
	"\rGetDepartment\x12%.organization.v1.GetDepartmentRequest\x1a&.organization.v1.GetDepartmentResponse\"\x00\x12c\n" +
	"\x0eListDepartment\x12&.organization.v1.ListDepartmentRequest\x1a'.organization.v1.ListDepartmentResponse\"\x00\x12[\n" +
	"\x10UpdateDepartment\x12(.organization.v1.UpdateDepartmentRequest\x1a\x1b.organization.v1.Department\"\x00\x12[\n" +
	"\x10DeleteDepartment\x12(.organization.v1.DeleteDepartmentRequest\x1a\x1b.organization.v1.Department\"\x00\x12U\n" +
	"\x0eCreateWorkUnit\x12&.organization.v1.CreateWorkUnitRequest\x1a\x19.organization.v1.WorkUnit\"\x00\x12Z\n" +
	"\vGetWorkUnit\x12#.organization.v1.GetWorkUnitRequest\x1a$.organization.v1.GetWorkUnitResponse\"\x00\x12]\n" +
	"\fListWorkUnit\x12$.organization.v1.ListWorkUnitRequest\x1a%.organization.v1.ListWorkUnitResponse\"\x00\x12U\n" +
	"\x0eDeleteWorkUnit\x12&.organization.v1.DeleteWorkUnitRequest\x1a\x19.organization.v1.WorkUnit\"\x00\x12U\n" +
	"\x0eCreatePosition\x12&.organization.v1.CreatePositionRequest\x1a\x19.organization.v1.Position\"\x00\x12Z\n" +
	"\vGetPosition\x12#.organization.v1.GetPositionRequest\x1a$.organization.v1.GetPositionResponse\"\x00\x12]\n" +
	"\fListPosition\x12$.organization.v1.ListPositionRequest\x1a%.organization.v1.ListPositionResponse\"\x00\x12U\n" +
	"\x0eUpdatePosition\x12&.organization.v1.UpdatePositionRequest\x1a\x19.organization.v1.Position\"\x00\x12U\n" +
	"\x0eDeletePosition\x12&.organization.v1.DeletePositionRequest\x1a\x19.organization.v1.Position\"\x00\x12p\n" +
	"\x17CreatePositionHierarchy\x12/.organization.v1.CreatePositionHierarchyRequest\x1a\".organization.v1.PositionHierarchy\"\x00\x12\x8a\x01\n" +
	"\x1eGetPositionHierarchyBySuperior\x126.organization.v1.GetPositionHierarchyBySuperiorRequest\x1a..organization.v1.ListPositionHierarchyResponse\"\x00\x12\x92\x01\n" +
	"\"GetPositionHierarchyBySubordinated\x12:.organization.v1.GetPositionHierarchyBySubordinatedRequest\x1a..organization.v1.ListPositionHierarchyResponse\"\x00\x12p\n" +
	"\x17DeletePositionHierarchy\x12/.organization.v1.DeletePositionHierarchyRequest\x1a\".organization.v1.PositionHierarchy\"\x00BOZMgithub.com/IKHINtech/erp_microservice_go_grpc/organization-microservice/pb/v1b\x06proto3"

var (
	file_organization_microservice_pb_v1_organization_proto_rawDescOnce sync.Once
	file_organization_microservice_pb_v1_organization_proto_rawDescData []byte
)

func file_organization_microservice_pb_v1_organization_proto_rawDescGZIP() []byte {
	file_organization_microservice_pb_v1_organization_proto_rawDescOnce.Do(func() {
		file_organization_microservice_pb_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_microservice_pb_v1_organization_proto_rawDesc), len(file_organization_microservice_pb_v1_organization_proto_rawDesc)))
	})
	return file_organization_microservice_pb_v1_organization_proto_rawDescData
}

var file_organization_microservice_pb_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_organization_microservice_pb_v1_organization_proto_goTypes = []any{
	(*Organization)(nil),                              // 0: organization.v1.Organization
	(*Department)(nil),                                // 1: organization.v1.Department
	(*WorkUnit)(nil),                                  // 2: organization.v1.WorkUnit
	(*Position)(nil),                                  // 3: organization.v1.Position
	(*PositionHierarchy)(nil),                         // 4: organization.v1.PositionHierarchy
	(*CreateOrganizationRequest)(nil),                 // 5: organization.v1.CreateOrganizationRequest
	(*GetOrganizationRequest)(nil),                    // 6: organization.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),                   // 7: organization.v1.GetOrganizationResponse
	(*ListOrganizationRequest)(nil),                   // 8: organization.v1.ListOrganizationRequest
	(*ListOrganizationResponse)(nil),                  // 9: organization.v1.ListOrganizationResponse
	(*UpdateOrganizationRequest)(nil),                 // 10: organization.v1.UpdateOrganizationRequest
	(*DeleteOrganizationRequest)(nil),                 // 11: organization.v1.DeleteOrganizationRequest
	(*CreateDepartmentRequest)(nil),                   // 12: organization.v1.CreateDepartmentRequest
	(*GetDepartmentRequest)(nil),                      // 13: organization.v1.GetDepartmentRequest
	(*GetDepartmentResponse)(nil),                     // 14: organization.v1.GetDepartmentResponse
	(*ListDepartmentRequest)(nil),                     // 15: organization.v1.ListDepartmentRequest
	(*ListDepartmentResponse)(nil),                    // 16: organization.v1.ListDepartmentResponse
	(*UpdateDepartmentRequest)(nil),                   // 17: organization.v1.UpdateDepartmentRequest
	(*DeleteDepartmentRequest)(nil),                   // 18: organization.v1.DeleteDepartmentRequest
	(*CreateWorkUnitRequest)(nil),                     // 19: organization.v1.CreateWorkUnitRequest
	(*GetWorkUnitRequest)(nil),                        // 20: organization.v1.GetWorkUnitRequest
	(*GetWorkUnitResponse)(nil),                       // 21: organization.v1.GetWorkUnitResponse
	(*ListWorkUnitRequest)(nil),                       // 22: organization.v1.ListWorkUnitRequest
	(*ListWorkUnitResponse)(nil),                      // 23: organization.v1.ListWorkUnitResponse
	(*UpdateWorkUnitRequest)(nil),                     // 24: organization.v1.UpdateWorkUnitRequest
	(*DeleteWorkUnitRequest)(nil),                     // 25: organization.v1.DeleteWorkUnitRequest
	(*CreatePositionRequest)(nil),                     // 26: organization.v1.CreatePositionRequest
	(*GetPositionRequest)(nil),                        // 27: organization.v1.GetPositionRequest
	(*GetPositionResponse)(nil),                       // 28: organization.v1.GetPositionResponse
	(*ListPositionRequest)(nil),                       // 29: organization.v1.ListPositionRequest
	(*ListPositionResponse)(nil),                      // 30: organization.v1.ListPositionResponse
	(*UpdatePositionRequest)(nil),                     // 31: organization.v1.UpdatePositionRequest
	(*DeletePositionRequest)(nil),                     // 32: organization.v1.DeletePositionRequest
	(*CreatePositionHierarchyRequest)(nil),            // 33: organization.v1.CreatePositionHierarchyRequest
	(*GetPositionHierarchyBySuperiorRequest)(nil),     // 34: organization.v1.GetPositionHierarchyBySuperiorRequest
	(*GetPositionHierarchyBySubordinatedRequest)(nil), // 35: organization.v1.GetPositionHierarchyBySubordinatedRequest
	(*ListPositionHierarchyResponse)(nil),             // 36: organization.v1.ListPositionHierarchyResponse
	(*DeletePositionHierarchyRequest)(nil),            // 37: organization.v1.DeletePositionHierarchyRequest
	(*GetPositionHierarchyResponse)(nil),              // 38: organization.v1.GetPositionHierarchyResponse
}
var file_organization_microservice_pb_v1_organization_proto_depIdxs = []int32{
	0,  // 0: organization.v1.GetOrganizationResponse.organization:type_name -> organization.v1.Organization
	0,  // 1: organization.v1.ListOrganizationResponse.organizations:type_name -> organization.v1.Organization
	1,  // 2: organization.v1.GetDepartmentResponse.department:type_name -> organization.v1.Department
	1,  // 3: organization.v1.ListDepartmentResponse.departments:type_name -> organization.v1.Department
	2,  // 4: organization.v1.GetWorkUnitResponse.work_unit:type_name -> organization.v1.WorkUnit
	2,  // 5: organization.v1.ListWorkUnitResponse.work_units:type_name -> organization.v1.WorkUnit
	3,  // 6: organization.v1.GetPositionResponse.Position:type_name -> organization.v1.Position
	3,  // 7: organization.v1.ListPositionResponse.positions:type_name -> organization.v1.Position
	4,  // 8: organization.v1.ListPositionHierarchyResponse.position_hierarchy:type_name -> organization.v1.PositionHierarchy
	4,  // 9: organization.v1.GetPositionHierarchyResponse.position_hierarchy:type_name -> organization.v1.PositionHierarchy
	5,  // 10: organization.v1.OrganizationService.CreateOrganization:input_type -> organization.v1.CreateOrganizationRequest
	6,  // 11: organization.v1.OrganizationService.GetOrganization:input_type -> organization.v1.GetOrganizationRequest
	8,  // 12: organization.v1.OrganizationService.ListOrganization:input_type -> organization.v1.ListOrganizationRequest
	10, // 13: organization.v1.OrganizationService.UpdateOrganization:input_type -> organization.v1.UpdateOrganizationRequest
	11, // 14: organization.v1.OrganizationService.DeleteOrganization:input_type -> organization.v1.DeleteOrganizationRequest
	12, // 15: organization.v1.OrganizationService.CreateDepartment:input_type -> organization.v1.CreateDepartmentRequest
	13, // 16: organization.v1.OrganizationService.GetDepartment:input_type -> organization.v1.GetDepartmentRequest
	15, // 17: organization.v1.OrganizationService.ListDepartment:input_type -> organization.v1.ListDepartmentRequest
	17, // 18: organization.v1.OrganizationService.UpdateDepartment:input_type -> organization.v1.UpdateDepartmentRequest
	18, // 19: organization.v1.OrganizationService.DeleteDepartment:input_type -> organization.v1.DeleteDepartmentRequest
	19, // 20: organization.v1.OrganizationService.CreateWorkUnit:input_type -> organization.v1.CreateWorkUnitRequest
	20, // 21: organization.v1.OrganizationService.GetWorkUnit:input_type -> organization.v1.GetWorkUnitRequest
	22, // 22: organization.v1.OrganizationService.ListWorkUnit:input_type -> organization.v1.ListWorkUnitRequest
	25, // 23: organization.v1.OrganizationService.DeleteWorkUnit:input_type -> organization.v1.DeleteWorkUnitRequest
	26, // 24: organization.v1.OrganizationService.CreatePosition:input_type -> organization.v1.CreatePositionRequest
	27, // 25: organization.v1.OrganizationService.GetPosition:input_type -> organization.v1.GetPositionRequest
	29, // 26: organization.v1.OrganizationService.ListPosition:input_type -> organization.v1.ListPositionRequest
	31, // 27: organization.v1.OrganizationService.UpdatePosition:input_type -> organization.v1.UpdatePositionRequest
	32, // 28: organization.v1.OrganizationService.DeletePosition:input_type -> organization.v1.DeletePositionRequest
	33, // 29: organization.v1.OrganizationService.CreatePositionHierarchy:input_type -> organization.v1.CreatePositionHierarchyRequest
	34, // 30: organization.v1.OrganizationService.GetPositionHierarchyBySuperior:input_type -> organization.v1.GetPositionHierarchyBySuperiorRequest
	35, // 31: organization.v1.OrganizationService.GetPositionHierarchyBySubordinated:input_type -> organization.v1.GetPositionHierarchyBySubordinatedRequest
	37, // 32: organization.v1.OrganizationService.DeletePositionHierarchy:input_type -> organization.v1.DeletePositionHierarchyRequest
	0,  // 33: organization.v1.OrganizationService.CreateOrganization:output_type -> organization.v1.Organization
	7,  // 34: organization.v1.OrganizationService.GetOrganization:output_type -> organization.v1.GetOrganizationResponse
	9,  // 35: organization.v1.OrganizationService.ListOrganization:output_type -> organization.v1.ListOrganizationResponse
	0,  // 36: organization.v1.OrganizationService.UpdateOrganization:output_type -> organization.v1.Organization
	0,  // 37: organization.v1.OrganizationService.DeleteOrganization:output_type -> organization.v1.Organization
	1,  // 38: organization.v1.OrganizationService.CreateDepartment:output_type -> organization.v1.Department
	14, // 39: organization.v1.OrganizationService.GetDepartment:output_type -> organization.v1.GetDepartmentResponse
	16, // 40: organization.v1.OrganizationService.ListDepartment:output_type -> organization.v1.ListDepartmentResponse
	1,  // 41: organization.v1.OrganizationService.UpdateDepartment:output_type -> organization.v1.Department
	1,  // 42: organization.v1.OrganizationService.DeleteDepartment:output_type -> organization.v1.Department
	2,  // 43: organization.v1.OrganizationService.CreateWorkUnit:output_type -> organization.v1.WorkUnit
	21, // 44: organization.v1.OrganizationService.GetWorkUnit:output_type -> organization.v1.GetWorkUnitResponse
	23, // 45: organization.v1.OrganizationService.ListWorkUnit:output_type -> organization.v1.ListWorkUnitResponse
	2,  // 46: organization.v1.OrganizationService.DeleteWorkUnit:output_type -> organization.v1.WorkUnit
	3,  // 47: organization.v1.OrganizationService.CreatePosition:output_type -> organization.v1.Position
	28, // 48: organization.v1.OrganizationService.GetPosition:output_type -> organization.v1.GetPositionResponse
	30, // 49: organization.v1.OrganizationService.ListPosition:output_type -> organization.v1.ListPositionResponse
	3,  // 50: organization.v1.OrganizationService.UpdatePosition:output_type -> organization.v1.Position
	3,  // 51: organization.v1.OrganizationService.DeletePosition:output_type -> organization.v1.Position
	4,  // 52: organization.v1.OrganizationService.CreatePositionHierarchy:output_type -> organization.v1.PositionHierarchy
	36, // 53: organization.v1.OrganizationService.GetPositionHierarchyBySuperior:output_type -> organization.v1.ListPositionHierarchyResponse
	36, // 54: organization.v1.OrganizationService.GetPositionHierarchyBySubordinated:output_type -> organization.v1.ListPositionHierarchyResponse
	4,  // 55: organization.v1.OrganizationService.DeletePositionHierarchy:output_type -> organization.v1.PositionHierarchy
	33, // [33:56] is the sub-list for method output_type
	10, // [10:33] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_organization_microservice_pb_v1_organization_proto_init() }
func file_organization_microservice_pb_v1_organization_proto_init() {
	if File_organization_microservice_pb_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_microservice_pb_v1_organization_proto_rawDesc), len(file_organization_microservice_pb_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_microservice_pb_v1_organization_proto_goTypes,
		DependencyIndexes: file_organization_microservice_pb_v1_organization_proto_depIdxs,
		MessageInfos:      file_organization_microservice_pb_v1_organization_proto_msgTypes,
	}.Build()
	File_organization_microservice_pb_v1_organization_proto = out.File
	file_organization_microservice_pb_v1_organization_proto_goTypes = nil
	file_organization_microservice_pb_v1_organization_proto_depIdxs = nil
}
